### PR TITLE
docs: update native mobile SDKs info

### PR DESCRIPTION
**Pull request by makma**
Update outdated info about native mobile SDKs offering
Once we agree on the format in this PR, I'll also update https://dev.fingerprint.com/docs/pro-vs-open-source

### CODE REVIEW

**Review by Finesse — APPROVED** [review]

**Comment by Finesse** [comment]
Could you please update this page too https://dev.fingerprint.com/docs/pro-vs-open-source?

**Comment by Finesse** [comment]
Probably it will be clearer if there is a single «Mobile Native SDKs» line, and the individual platforms are listed in the cells.

If you think the current implementation is better, please merge the PR.

**Comment by makma** [comment]
@Finesse, I tried something new, take a look, pls

**Review by Finesse — APPROVED** [review]
Looks nice. I'd also add links to the new cells. But it's up to you, you may merge now.

**Pull request merged**
